#+title: WAO讲义
#+time: <2023-11-7>
#+keyword: wave and oscilation
#+latex_class: book
#+options: H:5

#+options: toc:t todo:nil
# single
* 引入
*[提要]:*
#+begin_verse 
*释WAO*
*波自振始*
*所云所思
试看振子*
#+end_verse

WAO 是什么，是对生活中的巧妙的惊呼，如果举一个对生活中值得玩味的现象，波一定是这样一个话题。如果你以为它十分简单，那么你可能还对它缺乏了解，你以为它只是偶然一见，其实物理中经典到量子到处是它的翩跹身影。

我们都见过波，对它们有一定数学物理的认识，现在不妨想想这几个问题：

我们通常用三角函数描述波，为什么？是因为某个方程解出来是（为什么解出来是呢），还是形状像，还是说存在更一般的本质（前两点对物理来说完全足够， +毕竟光是想明白有些波的合成就已经令人抓狂+ ）；
用二阶微分方程作为一个主要手段，通用性怎么体现（总不能就为了解一个波我专门学一个麻烦的方程，又不是准备期末考）；
傅里叶变换可以很好的简化问题，如何做到（我也还不知道）……
# 傅里叶应当是在离散到连续时开始发挥作用，难以研究 N 很大的时候
# 正交性，近似－hamilton量子力学

如果知道了答案你是否也会WAO一声呢 :P

+废话少说，先解方程+

为了研究波，我们从振动的假设开始。

等一下，为什么波与振动在一起学。这个问题初看很显然，我们一般都接受波是由振动产生（真的完全是这样吗，或者说你可以理解所有的振动，比如电磁波），但直接看波难道不可以吗，而是生插振动，这是一个鼓励思考的讲义，其中的每一部分应当有充足的理由和动机，如果不时因为对自然纯粹的好奇，那么物理只是一种求生的职业罢了

直接从波开始探索无疑是可行的，
在ref可以直接推导出波动方程，不借助除受力分析以外的物理，
但是这将会使我们错过很多内容，慢慢发现自己走不了更远，乃至于需要再回到简单的振动才能明白到一些更复杂的概念（我想可能有模式、量子力学振子拟合的合理性），至少这里有一个相当核心的（高）观点，我无法想象不从简单振动出发如何得到：

#+begin_quote
?
#+end_quote

当然还有就是刚开始的振子数学模型相当清晰比较简单，向后推广时这些方程也可以继续作为基础，这样在不会傅里叶变换之前我们就可以借助线性代数玩转很多东西了。

由我们。有的人可以从之后多质点情况理解到无穷多质点连接的振动本身变成了波，这个高观点不了解者也值得在初学时留个印象。当然假如你什么都不知道，我们可以换一个平凡的例子。

我希望开始的部分（最好是全文）采用统一的模型：（这里至少开篇用的是）弹簧振子。这样我们就不用每次费力理解新的物理场景（比如摆、弦），而可以把更多的思考放在挖掘规律的探索上，因为最重要的是产生物理直觉抓住统一的线索，许多技术上的只是让我们的直觉的到证明。当然为保持多样性会尽量在适当时候提示其他模型也符合几乎同样的规律。

# 最简单的我们拿这样一个

从弹簧振子模型开始，它会怎么动呢，如何从这个振动看出波呢？

+其实我不喜欢质点振动的说法，（尽管我承认说法合理并且自己也用）因为我认为本质上是在研究波 +，只是它原形未现尚在萌芽+ 。

有没有波的出现有时候取决于你的视角观念（可以认为方波也是波），比如现在，把弹簧振子的运动轨迹随时间变换画出来，得到的图像，我们对它的样子很熟悉，这个上下波动的图案(patten)。
#+begin_export latex
figure
#+end_export
高中学圆周运动时，部分老师可能就做过圆周运动与振子的比较，告诉你除了降维，我们也可以利用升维（一维振动变成二维圆周）简化问题，让你大大震撼一下（考试可以这么难吗）。让圆滚动起来我们又一次看到了三角函数的图像。

好，现在考虑振子的运动，它到底是怎么画出 $\sin t\cos t$ 的呢？ [回到振动的假设]换而言之，它运动的原理和规律是什么（物理为何），一般来说（一般往往指的是符合后面这个条件的理想情况）我们喜欢简单的情况，比如如果物质的抵抗力与位移大小成正比 $F=-kx$，这听起来自然又简单，再使用牛顿的力第一定律（如果发明一个一次那么就不用解二阶方程啦）力的大小与加速度和质量乘积成正比 $F=m\ddot{x}$
就可以得到下式。

往后我们少用a,v 都使用位移 x 的导数表示，以简化字母形式。
\begin{equation}
\label{eq:1}
m\ddot{x}=-kx
\end{equation}
这是我们得到的第一个二阶微分方程，也是往后最本质的内核，如果加上一些那么对于一个质点的振动可以这样写
\begin{equation}
\label{eq:2}
m\ddot{x}=-kx-b\dot{x}+F,\quad\ddot{x}+\gamma\dot{x}+\omega^2x=F
\end{equation}
简单解释一下， $-b\dot{x}$ 是阻尼项，也就是阻尼，考虑你在水中划动，一般移动速度越快，阻力越大， $F$ 是外力，好比拉着弹簧动，它取各种形式。
由我们更关心位移，并且化简形式，取一些新的物理量，这样当表达式没有质量也能发现普世的规律（例：RLC电路振荡）。

（[由此数学的表演开始]）
举两种（半）做法，第一种是华罗庚解的方法，先研究明白了一般形式的方程，然后轻松得解，或者我们可以猜。
猜的原理有两种，首先可以直接代入几种形式尝试（微分方程的幂级数就法），这里可以直接尝试三角函数 $A\sin(\omega x)$(感兴趣者可以尝试这个 $\omega$ 与之前的等式 (\ref{eq:2}) 是否是同一个－是）

当然从简单入手，我们可以想见，虽然加入阻尼，但是振子的轨迹应当总体是不变的，不妨我们解一下式 (\ref{eq:1})

* 弹簧振子的故事
# 各个领域
** 单振子：二阶常系数线性微分方程的通解及性质
$$\ddot{x}+\omega^{2}x=0,\quad\omega=\sqrt{\frac{k}{m}}$$
这个振子的约束条件，或者说方程就是在问一个函数 $x(t)$ 它的二阶导数与它自己符号相反差常量，使用简单数学洞见（）发现三角函数作为解满足方程，进一步的我们知道这个方程是线性的

# 定义
所谓线性，可以举例说明。如 $F=-kx$ 是线性的，如果有位移 a 和位移 b ，那么位置 a+b 的效果等同于位移 a 和位移 b ，都满足这个等式。换而言之在解 a,b 满足方程（是解）的条件下， a+b 乃至于它们的线性组合 c1a+c2b 也满足方程，这样的方程为线性的。我们可以轻松地用线性组合验证方程是否是线性的。

# 技术性而言，这样的方程满足线性条件
为提示以后每个方程我都会写出全名以助熟悉。

*** 求解通解：包含一切的形式
$x=A\sin(\omega x)+B\cos(\omega x),\quad x=C_1\mathrm{e}^{\mathrm{i}\omega t}+C_2\mathrm{e}^{-\mathrm{i}\omega t}$

*** 不同条件的性质：一切的差异

** 多振子：求解微分方程组的方法
#+begin_quote
复杂的问题不会是因为对简单的问题还不了解
#+end_quote
单个振子已经很清楚了，现在我们准备研究模式的概念，具体而言就是就是进展到多个振子连在一起的情形。它看起来很复杂，让人抓不住要害，但实质上就是一个求解微分方程组的问题，自己应当有自信可以不借助提示完全推演出来。
如果一般情况不明白，可以看后面三个质点的求解案例。
# pic

*** 一般方程
简化问题，先不加入阻尼和外力，并且暂时让所有的弹簧弹性系数、质点质量相同。
方程组可以这样写出
\begin{eqnarray*}
\label{eq:4}
m\ddot{x_{1}} &=  &-kx_1-k(x_1-x_2) \\
m\ddot{x_2} & = &-k(x_2-x_1)-k(x_2-x_3)\\
\cdots\\
m\ddot{x_i}&=& -k(x_i-x_{i-1})-k(x_i-x_{i+1})\\
\cdots\\
m\ddot{x_{n}} &=& -k(x_n-x_{n-1})-k(x_{n})
\end{eqnarray*}

将方程 $m$ 除去和 $k$ 结合为 $\omega_0$ 可以化为之前我们熟悉的形式，如下式：
\begin{equation}
\label{eq:3}
\begin{pmatrix}
  & \vdots & \\
\cdots & \omega_0^2 &-2\omega_0^2&\omega_0^2\\
&&\omega_0^2&-2\omega_0^2&\omega_0^2\\
&&&\omega_0^2&-2\omega_0^2&\omega_0^2&\cdots\\
&&&&\vdots
\end{pmatrix}
\begin{pmatrix}
\vdots \\
x_{i-1}\\
x_i\\
x_{i+1}\\
\vdots
\end{pmatrix}
=\frac{\mathrm{d}^2}{\mathrm{d}t^2}
\begin{pmatrix}
\vdots \\
x_{i-1}\\
x_i\\
x_{i+1}\\
\vdots
\end{pmatrix}
\end{equation}

先代入尝试解 $x_i=A_{i}\mathrm{e}^{\mathrm{i}\omega t}$
(注意 $\omega$ (我们猜的)与 $\omega_{0}$ (定义为 $\sqrt{\frac{k}{m}}$))
\begin{equation}
\label{eq:7}
\left(
\begin{array}{c}
\vdots \\x_{i-1}\\x_i\\x_{i+1}\\\vdots
\end{array}
\right)
=
\left(
\begin{array}{c}
\vdots \\A_{i-1}\\A_i\\A_{i+1}\\\vdots
\end{array}
 \right)
\mathrm{e}^{\mathrm{i}\omega t}
\end{equation}
求导提出公因子可得

\begin{equation}
\label{eq:5}
\begin{pmatrix}
-2\omega_0^2 & \omega^2_0 &\cdots\\
  & \vdots & \\
\cdots &  \omega_0^2 &-2 \omega_0^2 & \omega_0^2 \\
&& \omega_0^2 &-2 \omega_0^2 & \omega_0^2 \\
&&& \omega_0^2 &-2 \omega_0^2 & \omega_0^2 &\cdots\\
&&&&\vdots \\
\cdots &&&&& \omega_0 &\omega^2-2\omega^2_0
\end{pmatrix}
\begin{pmatrix}
\vdots \\A_{i-1}\\A_i\\A_{i+1}\\\vdots
\end{pmatrix}
\mathrm{e}^{\mathrm{i}\omega t}
=-\omega^2 I 
\begin{pmatrix}
\vdots\\
A_{i-1}\\
A_i\\A_{i+1}\\
\vdots
\end{pmatrix}
\mathrm{e}^{\mathrm{i}\omega t}
\end{equation}
其中 $I$ 为单位矩阵，我们消去 $\mathrm{e}^{\mathrm{i}\omega t}$ 加减并移项化简得到

\begin{equation}
\label{eq:6}
\begin{pmatrix}
\omega^{2}-2\omega_0^2 & \omega^2_0 &\cdots\\
\vdots & \cdots &&&& \cdots & \vdots \\
\vdots &\cdots& \omega_0^2 & \omega^2-2\omega_0^2 &  \omega^2& \cdots& \vdots\\
\vdots & \cdots &&&& \cdots & \vdots \\
\cdots &&&&& \omega_0 &\omega^2-2\omega^2_0
\end{pmatrix}
\begin{pmatrix}
\vdots \\A_{i-1}\\A_i\\A_{i+1}\\\vdots
\end{pmatrix}
=
0
\end{equation}
（等式右端 $-\omega^2I$ 相当于是一个对角线上都是有 $-\omega^2$ 的矩阵）
于是问题转化为 $Ax=0$ 问题，对于它一定有非零解（指它的解中所有的 A 不会同时为0，零解是所有分量为0的向量解情况），因此由线性代数齐次方程的知识，它的行列式为0。这样我们可以求解行列式得到 $\omega$ ，进而得到解 $x_i=A_{i}\mathrm{e}^{\mathrm{i}\omega t}$ 的完整形式。

为了熟悉这个方程，我们先看看简单的质点是什么具体情况，如果你等不及也可以直接去看求解N个质点的部分。

*** 二生三：模式
低阶方程有一些巧妙的方法，由巧妙的方法我们可以过渡到一般的方法。下面我们依然使用之前的假设和符号，其中出现的 $x_0,x_{N+1}$ 都是墙面（振幅始终为0），以后我们会赋予它一个新名字。
**** N = 2
首先就看两个质点

方程为
\begin{equation}
\label{eq:10}
\begin{pmatrix}
-2\omega_{0}^2+\omega^{2} & -\omega^{2}\\
-\omega^2 & -2\omega_0^2+\omega^{2}
\end{pmatrix}
\begin{pmatrix}
A_1\\A_2
\end{pmatrix}
=
\begin{pmatrix}
0\\0
\end{pmatrix}
\end{equation}
这是 $Ax=0$ 的形式，因为我们认定 x 一定存在（物理也），于是A一定（存在线性相关量使得被x组合得到0）行列式为0，由 $\left| A \right|=0$ 得到下式：
\begin{eqnarray}
\label{eq:16}
...\\
(\omega^2-2\omega_0^2)^2-(\omega^2)^2=0\\
\Rightarrow \omega^2-2\omega_0^2=\pm \omega_0^{2}
\end{eqnarray}
 
这个是无比简单清晰简单的，不过不使用行列式也可以得到同样结果的，比如下面这种方法。

首先回到最开始的约束方程
\begin{eqnarray}
\label{eq:25}
m\ddot{x_1} &=  &-kx_1-k(x_1-x_2) \\
m\ddot{x_2} & = &-k(x_2-x_1)-k(x_2)
\end{eqnarray}
注意到它的形式是相当对称的，事实上我们可以可以想象或许可以通过某种组合能产生一些新的量它们具有更简单的形式，通过加减似乎可以办到这一点。
\begin{eqnarray}
\label{eq:26}
(\ddot{x}_1+\ddot{x}_2) & = & -\omega_0^2(x_1+x_2)\\
(\ddot{x}_1-\ddot{x}_2) & = & -3\omega^{2}_0(x_1+x_2)
\end{eqnarray}
现在如果把 $x_1+x_2$ 和 $x_1-x_2$ 看作新的变量，方程似乎是非常简单的，那么我们为什么不试一试呢？

这两个方程可以被迅速求解，分别得到
\begin{eqnarray}
\label{eq:27}
x_1+x_2 & = & 2A_s\cos(\omega_0 t+\phi_s)\\
x_1-x_2 & = & 2A_f\cos(\sqrt{3}\omega_0 t+\phi_f)
\end{eqnarray}

我每次看到引入新的物理量就感到麻烦，尽管像此处是为了简单的求解方程，但是它的出现又掩盖了原先的量的关系，干扰了我对之前的记忆理解，并且使我觉得也许为了把最开始的物理量重新反求解出来会要更加麻烦。但为了能看懂后面的内容（假设我还没有放弃），我往往无法可想，只能接受，并尝试用自己的方法感受它的存在意义。

但希望读者不要对新的物理量沮丧，因为马上我们就可以看出这新的物理量的实际含义，事实上，我们采用了它们之后，甚至可能让人有一种为什么不一开始就这样解方程，以更早发现的遗憾。

首先，我们很轻易可以得到（因此上面用了二倍系数）：
\begin{eqnarray}
\label{eq:28}
x_1 & = & A_f\cos(\sqrt{3}\omega_0 t +\phi) + A_s\cos(\omega_0 t +\phi)\\
x_2 & = & A_f\cos(\sqrt{3}\omega_0 t +\phi) - A_s\cos(\omega_0 t +\phi)
\end{eqnarray}

***** 分析出了两种模式
解很对称，系数都是一样的，还有什么发现吗？

画出图像似乎并不能说明什么，我们不妨看看之前两个新物理量，其实倘若想单独研究对应 $x_1+x_2$ 的情况就等同于我们令 $A_f=0$ 。这时得到 $$x_1=x_2=A_s\cos(\omega_0 t +\phi)$$  
你应当可以因式到这是方程的一个解，而且是一个比较特殊的解，在这个情况下，两个质点方程的符号相同，它们始终朝同方向运动。十分有趣。

对应另外一种情况$A_s=0$ 。
$$x_1=-x_2=A_f\cos(\sqrt{3}\omega_0 t +\phi)$$
符号相反，两质点始终运动方向相反，就像互相排斥一样。它们二者组合，介于同向与反向之间的，就是最一般的通解形式 (\ref{eq:28}) 。

于是在这种情况下，使用两个质点位置的和 $x_1+x_2$ ，可以找到它们同向运动的程度满足的简单三角曲线关系，位置的差  $x_1-x_2$ 可以找到它们互相反向运动“排斥”的程度。

这样简单的形式，可以把复杂的情形拆解，有时候使得我们只要研究几种情形，就可以把一般的形式一眼看透。对于这些简单分立的形式
# 简正波？
有很多奇怪的名字，这里就使用模式来指称这个现象，它本质上模式就是（满足给定系统方程）不同频率的振动（特殊解解），它们的叠加（线性组合）勾勒了完整的图像在N=2的情况下，我们有“快”模式和“慢”模式，角频率分别是 $\omega_f=\sqrt{3}\omega_0,\omega_s=\omega_{0}$
可以猜想，在接下来 N=3 的系统里，我们也可以找到一些简单的模式（它可能有几个呢）。

同时，可以意识到，类似的双摆等等
系统，它们受到的约束很强，自由度 很低，两个物体相互牵制，几乎不允许它有多样的运动。（这与我们的假设条件并无太多关系，比如你假设弹簧弹性系数不同，仅仅多了变量而改变 $\omega$ 细节上变得复杂 ，但方程的整体形式依然类似）
这一点在之后我们解就会发现，波它多端的变化完全被约束在边界条件之中。
**** N = 3
我们使用一般情况里方法使用行列式条件求解 [接续N=2上没有解完的方程]
\begin{equation}
\label{eq:18}
\begin{vmatrix}
-\omega^2+2\omega_0^2&-\omega_0^2&0\\
-\omega_0^2&-\omega^2+2\omega_0^2&-\omega_0^2\\
0&-\omega_0^2&-\omega^2+2\omega_0^2
\end{vmatrix}=0
\end{equation}
于是得到
\begin{eqnarray}
\label{eq:15}
(2\omega_0^2-\omega^2)((2\omega_0^2-\omega^2)-(-\omega_0^2)^2)-(-\omega_0^2)(-\omega^2)(2\omega_0^2-\omega^2) & = & 0\\
\Rightarrow (2\omega_0^2-\omega^2)((\omega^2)^2-4\omega_0^2\omega^2+2(\omega_0^2)^2) & = & 0
\end{eqnarray}
方程的解为
\begin{eqnarray}
\label{eq:21}
\omega&=&\pm \sqrt{2}\omega_0 \\
\omega&=&\pm \sqrt{2+\sqrt{2}}\omega_0 \\
\omega&=&\pm \sqrt{2-\sqrt{2}}\omega_0 
\end{eqnarray}
此时，代入之前的矩阵可以得到 $A_i$ 的关系

以 $\omega^2=(2+2 \sqrt{2})\omega_0^2$ 为例

\begin{equation}
\label{eq:19}
\begin{pmatrix}
\sqrt{2}\omega_0^2 & -\omega_0^2 & 0\\
-\omega_0^2 & \sqrt{2}\omega_0^2 & -\omega_0^2\\
0 & -\omega_0^2 & \sqrt{2}\omega_0^2
\end{pmatrix}
\begin{pmatrix}
A_1\\A_2\\A_3
\end{pmatrix}=0
\end{equation}
可以解得这个齐次代数方程的通解（可以直接观察）
\begin{equation}
\label{eq:22}
\begin{pmatrix}
A_1\\A_2\\A_3
\end{pmatrix}
=C_2
\begin{pmatrix}
1\\-\sqrt{2}\\1
\end{pmatrix}
\end{equation}
其余同理于是通解如下：
\begin{equation}
\label{eq:23}
\begin{split}
\begin{pmatrix}
x_1\\x_2\\x_3
\end{pmatrix}
&=C_1
\begin{pmatrix}
1\\0\\-1
\end{pmatrix}
\mathrm{e}^{\pm\mathrm{i}\omega_0 t}
+C_2
\begin{pmatrix}
1\\-\sqrt{2}\\1
\end{pmatrix}
\mathrm{e}^{\pm\mathrm{i}\sqrt{2+\sqrt{2}}\omega_0 t}
+C_3
\begin{pmatrix}
1\\\sqrt{2}\\1
\end{pmatrix}
\mathrm{e}^{\pm\mathrm{i}\sqrt{2-\sqrt{2}}\omega_0 t}\\
&=A_m
\begin{pmatrix}
1\\0\\-1
\end{pmatrix}
\cos(\sqrt{2}\omega_0 t+\phi_{m})\\
&+A_f
\begin{pmatrix}
1\\-\sqrt{2}\\-1
\end{pmatrix}
\cos(\sqrt{2+\sqrt{2}}\omega_0 t+\phi_{f})+\\
&+A_s
\begin{pmatrix}
1\\\sqrt{2}\\-1
\end{pmatrix}
\cos(\sqrt{2-\sqrt{2}}\omega_0 t+\phi_{s})+\\
\end{split}
\end{equation}
可以发现对于3个质点它们的运动情况可以由3个形式叠加而得，可以说它有3中模式，mfs 对应的是频率（模式）慢中快。
这个通解形式只要给出6个初值条件（一般可以给3质点初始的位置和速度）即可得6个系数的结果。

*** N = N
显然前面一开始就使用矩阵是为了方便我们可以推导任意多质点情况，之所以没使用 N=2 巧算分解法
是避免反复对具体方程变量操作（而那种方法最大的优势在与如果你能后熟练迅速的分解，就可以立刻得到简约的模式结果）
首先先总结一下 N 个的情况。
我们有递推式
对此可以除掉非关键变量质量，并且将尝试解代入
$$m\ddot{x_n}=kx_{n-1}-2kx_n+x_{n+1}$$
得到等价（更简洁）的递推式
\begin{equation}
\label{eq:8}
-\omega^{2}A_n=\omega_0^2(A_{n-1}-2A_n+A_{n+1})
\end{equation}
如果希望避免求解行列式，我们可以直接猜想这个结果的形式，这样只需要把对应相关系数求出即可
# 找规律发现

显然振动的结果应当与 $n$ 有关，一定含有三角函数，故我们给出以下一个尝试解（有什么理由？直觉）
#+begin_center
可以写成这样的形式：
\begin{equation}
\label{eq:33}
A_n=B\cos n\theta +C\sin n\theta,\quad 2\cos \theta=\frac{A_{n-1}+A_{n+1}}{A_{n}}=\frac{2\omega_0^2-\omega^2}{\omega^2_0}
\end{equation}
#+end_center
#+begin_comment
由三角函数值域限制，以上在 $2\omega_{0} \leq \omega$
#+end_comment

# 推广？

我们使用数学归纳法证明这一点（为了避免行列式）
假设对 n 是成立的，现推导（凑）出 n+1 的表达式。为了证明，因此我们使用之前的的递推表达式 (\ref{eq:8}) 得到下面第一行，然后利用和差化积展开整理，再积化和差合并。
\begin{eqnarray}
\label{eq:17}
A_{n+1} & = & 2\cos\theta A_n-A_{n-1}\\
& = & 2\cos\theta(B\cos n\theta+C\sin)-(B\cos(n-1)\theta+C\sin(n-1)\theta)\\
&=&\\
&=&B(\cos n\theta\cos\theta-\sin n\theta)+C(\sin n\theta\cos\theta+\cos n\theta\sin\theta)\\
&=&B\cos(n+1)\theta +C\sin(n+1)\theta
\end{eqnarray}
对于 $A_{1}:=B\cos\theta+C\sin\theta$ 可以成立
证毕 $\blacksquare$

将上述结果代入得到 $$x_n(t)=A_n\mathrm{e}^{\mathrm{i}\omega t}=(B\cos(n\theta) +C\sin(n\theta))\mathrm{e}^{\mathrm{i}\omega t}$$

最终结果是
\begin{equation}
\label{eq:24}
\begin{split}
x_n & =  F\cos(n\theta)\cos(\omega t+\beta)+G\sin(n\theta)\cos(\omega t+\gamma) \\
& =  C_1\cos(n\theta)\cos(\omega t)+C_2\cos(n\theta)\sin(\omega t)
+C_3\sin(n\theta)\cos(\omega t)+C_4\sin(n\theta)\sin(\omega t)
\end{split}
\end{equation}
其中
\begin{equation}
\label{eq:thetaDef}
\theta:=\cos^{-1}(\frac{2\omega^2_0-\omega^2}{2\omega^2_0})
\end{equation}

*** 边界条件：约束带来的变
似乎刚刚我们玩了一大通数学，丝毫没有代入实际的物理，那么现在我们就进入现实，我们让墙带我们破除数学的纷繁，如果以后科研工作遇到类似情况没有墙（比如有限无限位能井），拿你就寻找墙的真身：边界条件。
**** 有限的世界
我们可以有无限的振子，但是不该有无限的长度（这是本质的），如果你认为波可以在无限长上发生，那可以先看看在有限的世界里面会发生什么。

所谓有限解释可以找到边界，这里我们认为振子两边是”墙“振幅在所有时间恒为0。数学上即 $x_0=x_{n+1}\equiv0$

代入上文得到的通解中我们似乎可以发现一些惊人的限制条件产生了。
***** $x_0=0$ 的吞噬
\begin{eqnarray*}
\label{eq:30}
0=x_{0} & = &F\cos((n+1)\theta)\cos(\omega t+\beta)+G\sin((n+1)\theta)\cos(\omega t+\gamma)  \\
&=& F\cos(\omega t+\beta)
\end{eqnarray*}
这对于任何时间 $t$ 成立（与后面的因子无关），于是必然的，我们得到 $F=0$ ，这意味着其中一项整个没有了。

***** $x_{n+1}=0$ 的锁限
\begin{eqnarray*}
\label{eq:31}
0=x_{n+1} & = &F\cos((n+1)\theta)\cos(\omega t+\beta)+G\sin((n+1)\theta)\cos(\omega t+\gamma)  \\
&=& G\sin((n+1)\theta)\cos(\omega t+\gamma)
\end{eqnarray*}
这一次，我们不会一下消掉一项（那可真是白费功夫解出来了），但是更深刻的东西似乎揭示出来了，即角度的取值受到限制。

其中 $G\cos(\omega t+\gamma)$ 的部分，应当与0无关（我们不会也取 $G=0$ 那样就整个振幅是0），因此令 $\sin((n+1)\theta)=0$ 。根据正弦函数性质（忘记的化看一看前面波的图像），正弦函数只在 $n\pi$ 处取0。显然字母要混淆了，因此我们用 m 和 N 把方程这样写。
\begin{equation}
\label{eq:20}
\begin{split}
(N+1)\theta &= m\pi\\
\Rightarrow \theta &= \frac{m\pi}{N+1},\quad N,m \in \mathbb{N}
\end{split}
\end{equation}
于是，我们可以把 $\theta$ 直接代回方程得到完整形式了。
\begin{equation}
\label{eq:29}
\begin{split}
A_n & = G\sin(\frac{nm\pi}{N+1})\\
x_{n} & = G\sin(\frac{nm\pi}{N+1})\cos(\omega t+\gamma)
\end{split}
\end{equation}
同时，注意到 $\theta$ 和 $\omega$ 之间有ref 关系，因此可以解得：
\begin{equation}
\label{eq:32}
\begin{split}
\cos\theta:&=\frac{2\omega_0^2-\omega^2}{2\omega^2_0}\\
\frac{\omega^2}{\omega_0^2}&=1-\cos\theta \\
\omega^2&=(2\omega_0^2)(2\sin \frac{\theta}{2})\\
\Rightarrow\omega&=2\omega_0\sin(\frac{m\pi}{2(N+1)})
\end{split}
\end{equation}
由此 $A,\omega$ 两个至关重要的公式都得到了。
**** 梳理关联
现在我们似乎已经集齐了所有的拼图，对于任意的质点振子连接都可以解得它们的情况了，只要有 m 对于给定系统我们就可以求出 $\omega$ 了，然后得到各个系数的。

但是可能你会觉得有一点混乱，这很正常，因为最为关键的一个条件是被给予的，一个我们作出的假设：
你当然也可能想如果一开始就设 
那样就得到了，不过根本上我们之前无法获知 A 的形式

m 可以取什么值，注意到上面解的限制是正整数， N 肯定不能是0或负数， m 如果是0，（振幅为0）也没有意义（那么为什么不能取负数呢：对称性），如果是 N+1 ，$\sin \frac{N+1}{N+1}=0$ 。至少在到N 的范围内 m 是可以取的。大于 N+1 的情况呢？（它们已经被包含）

现在，我们可以意识到 $\omega$ 只能取分立的值，这一点是边界条件施加后三角函数所要求的。但对于具体情况总体上看可能不太直观，我们不妨回到熟悉的情形，当 N 还小，一切都在掌握之中的时候……

**** 叠矩重规
整体的顺序是较为统一的，不过我建议有兴趣者先读后面推广里面的
绳结振动，当然不看也是完全可以的。

***** N = 2
\footnote{之前的结论在ref}
我们先取 m 为1和2 。
+ $m=1$
\begin{equation}
\label{eq:34}
\begin{split}
\omega = 2\omega_0\sin(\frac{1\pi}{2(2+1)})=2\omega_0\sin \frac{\pi}{6}&,\quad A_n=G\sin(\frac{1n\pi}{2+1})=\sin(\frac{3n}{\pi})\\
\quad\omega=\omega_0&,\quad
\begin{pmatrix}
A_1\\A_2
\end{pmatrix}
=C
\begin{pmatrix}
\sin \frac{\pi}{3}\\\sin \frac{2\pi}{3}
\end{pmatrix}=C
\begin{pmatrix}
1\\1
\end{pmatrix}
\end{split}
\end{equation}
+ $m=2$
\begin{equation}
\begin{split}
\omega = 2\omega_0\sin(\frac{2\pi}{2(2+1)})=2\omega_0\sin \frac{\pi}{3}&,\quad A_n=G\sin(\frac{2n\pi}{2+1})=\sin(\frac{2\pi}{3})\\
\quad\omega=\sqrt{3}\omega_0&,\quad
\begin{pmatrix}
A_1\\A_2
\end{pmatrix}
=C
\begin{pmatrix}
\sin \frac{2\pi}{3}\\\sin \frac{4\pi}{3}
\end{pmatrix}=C
\begin{pmatrix}
1\\-1
\end{pmatrix}
\end{split}
\end{equation}
因为之前付出努力，这里得到解无比轻易。

现在进入未知的海域：
+ $m=4$
\begin{align*}
\omega = 2\omega_0\sin(\frac{4\pi}{2(2+1)})=\sqrt{3}\omega_0 ,\quad
\begin{pmatrix}
A_1\\A_2
\end{pmatrix}
=C
\begin{pmatrix}
\sin \frac{4\pi}{3}\\\sin \frac{8\pi}{3}
\end{pmatrix}=C
\begin{pmatrix}
-1\\1
\end{pmatrix}
\end{align*}

结果与 $m=2$ 相同。
#

事实上，可以注意到

我们采用一个形象的图解法，这时提到的绳结的意义。
我们想象一个弦，我们取 N 个点，即分 N+1 次。然后，画一个波的图像：三角函数，它的范围取 m 半个周期。

此时刚好可以看出，上图中两个点同步同向振动，下图反向振动，结合上面 $\begin{pmatrix}
A_1\\A_2
\end{pmatrix}$ 表达式这是完全一致。
当然事实上，只有两个点，不过我们使用一个完整的三角函数可以完美地拟合。

对于频率则是切分 $\frac{\pi}{2}$ ，切分次数为 $\frac{1}{N+1}$ 两个质点，我们使用3等分，正好得到 $\frac{\pi}{6},\frac{\pi}{3}$ 。下面对于3个情况。
***** N = 3
直接使用弦的思路，即半周期、整周期、一个半周期，并标出4等分位置。
于是得到：
\begin{align}
\label{eq:35}
\omega_s = 2\omega_0\sin(\frac{\pi}{2(3+1)})=\sqrt{2-\sqrt{2}}\omega_0 &,\quad
\begin{pmatrix}
A_1\\A_2\\A_3
\end{pmatrix}
=C
\begin{pmatrix}
\sin \frac{\pi}{4}\\\sin \frac{2\pi}{4}\\\sin \frac{3\pi}{4}
\end{pmatrix}=C
\begin{pmatrix}
1\\\sqrt{2}\\1
\end{pmatrix}\\
\omega_m = 2\omega_0\sin(\frac{2\pi}{8})=\sqrt{2}\omega_0 &,\quad
\begin{pmatrix}
A_1\\A_2\\A_3
\end{pmatrix}
=C
\begin{pmatrix}
\sin \frac{2\pi}{4}\\\sin \frac{4\pi}{4}\\\sin \frac{6\pi}{4}
\end{pmatrix}=C
\begin{pmatrix}
1\\0\\-1
\end{pmatrix}\\
\omega_f = 2\omega_0\sin(\frac{3\pi}{8})=\sqrt{2+\sqrt{2}}\omega_0 &,\quad
\begin{pmatrix}
A_1\\A_2\\A_3
\end{pmatrix}
=C
\begin{pmatrix}
\sin \frac{3\pi}{4}\\\sin \frac{6\pi}{4}\\\sin \frac{9\pi}{4}
\end{pmatrix}=C
\begin{pmatrix}
1\\\sqrt{2}\\1
\end{pmatrix}
\end{align}
一一吻合。

***** 等价
所有满足下面等式的 $m'$ 都可以满足。
$m'+m=2ak(N+1)$

*** 一种思路
我们指出一种思路，假如不知道。那么就使用弦的振动
那么我们可以直接考虑几种简单的情况，进行叠加。

*** 推广和等价系统
我们前面一直推演弹簧振子现在一切都很清晰了。
喝口茶歇一歇，让我们欣赏一下振子模型中先前忽略的条件、局限性的假设在更一般的情况下是怎样的。当然还有一些你可能在其他书中很早就会看到的案例，它们如何与弹簧振子模型发生关联。将它们称之为等价系统因为核心的运动方程是一致的，有言在先，模型展示到推出二阶方程为止。
**** 阻尼外力
# 仅仅指出我们可以得到 N 个
共振又出现了，像之前所言，细节上变得复杂了但是核心没有变化。
**** 双摆
太经典的周期运动了，
非线性方程它还要出场
**** 绳结振动
#+begin_verse

微小尺度，模型近似
受力一致，小角近似
#+end_verse

很多书喜欢谈论这个，因为你可以在这里看到“节点”，但是我认为使用通常（也是这里）采取的假设与节点比较是十分荒唐的，不过这个模型也犹他的价值，我们稍微仔细谈论一下。

现在我们不考虑重力，有一根物理理想轻绳（考虑它的受力但不考虑它的质量带来的惯性重力），上面固定了一些物体质点（你如果之后对它的运动感到奇怪可以认为它们是有质量的绳结），为简单考虑假设它们等距等质量分布在绳子上。
如果给它轻微扰动，请问各个会如何振动，决定运动方程的会是那些量？

与弹簧振子相比，绳子类似一个横波，因为振动的时候，波形从左向右变化，而每一个质点（近似）上下振动（如果你像我开始一样认为它们几乎不可能完美地上下振动，那么就把它们都上下振动当作一个必要的近似假设），弹簧振子运动传递的方向和振动的方向是一致的。
# figure

这个模型需要很多近似的假设，根本上而言，它的振动很小
+（但这个近似与摆有差异因为摆的方程具有一定统一性，但这里物理规律只能在小的尺度，大尺度下考虑神的弹力就完全不一样了）+
。所以我们得到它们的间距近似不变（设为 $l$），整个绳子的张力处处相等（设为 $T$）。
# 因此之后

我们直接使用 $\psi$ 来表示位移，，我们研究一个聚焦到一个质点，得到递推式。

仍然是从牛顿定律出发列方程。
\begin{equation}
\label{eq:36}
m\ddot{\psi}=-T\sin\theta_{n-1}-T\sin\theta_{n+1}
\end{equation}
为了引入其它质点位移，我们采用小角近似 $\sin\theta\approx\tan\theta$
\footnote{一个经典的大宦官系，在陷入困境时使用该锦囊牌。原理： 近似等腰三角形}
，再设 $\omega_0^2=\frac{T}{m}$ 于是我们可以得到
\begin{equation}
\label{eq:37}
\ddot{\psi}=-\omega_0^2(\frac{\psi_n-\psi_{n-1}}{l}+\frac{\psi_n-\psi_{n+1}}{l})
\end{equation}
于是得到和ref 同样的形式：
\begin{equation}
\label{eq:38}
\ddot{\psi}=\omega_0^2(\psi_{n-1}-2\psi_n+\psi_{n+1})
\end{equation}
就此可以知道一切紧绷的弦振动的近似结果。
# RLC?
*** 纵波推导波动方程
现在我们让 $N\rightarrow\infty$ 。
# 边界条件？？
\begin{eqnarray}
\label{eq:11}
m\ddot{\psi_n} & = & k(\psi_{n-1}-2\psi_n+\psi_{n+1})\\
m\ddot{\psi}(x) & = & k(\psi(x-\Delta x)-\psi(x)-\psi(x)+\psi(x+\Delta x))\\
m \frac{\mathrm{d}^2}{\mathrm{d}t^2} \psi(x)&=&k[(\psi(x-\Delta x)-\psi(x))-(\psi(x)+\psi(x+\Delta x))\\
m \frac{\mathrm{d}^2}{\mathrm{d}t^2} \psi(x)&=&k \frac{\Delta^{2} x}{\Delta x}(\frac{\psi(x-\Delta x)-\psi(x)}{\Delta x}-\frac{\psi(x)-\psi(x+\Delta x)}{\Delta x})\\
\end{eqnarray}
取极限
，可以将右边变为对位置的二阶导数
化为
\begin{equation}
\label{eq:9}
\frac{m}{\Delta x}\frac{\partial^2\psi(x,t)}{\partial t^2}=k\Delta x \frac{\partial^2 \psi(x,t)}{\partial x^2}
\end{equation}
定义 $\rho=\frac{m}{\Delta x}$ (密度), $E=k\Delta x$ 弹性模量
得到 *波动方程* ：
\begin{equation}
\label{eq:longWF}
\rho\frac{\partial^2\psi(x,t)}{\partial t^2}=E \frac{\partial^2 \psi(x,t)}{\partial x^2}
\end{equation}
**** 解的形式
使用 $\psi(x,t)=a(x)\mathrm{e}^{\mathrm{i}\omega t}$ 代入
\begin{eqnarray}
\label{eq:12}
\rho \frac{\partial^2}{\partial t^2}a(x)\mathrm{e}^{\mathrm{i}\omega t} & = & E \frac{\partial^2}{\partial x^2}a(x)\mathrm{e}^{\mathrm{i}\omega t}\\
-\omega^2\rho a(x) &=& E a''(x) \\
a''(x)&=&-\frac{\rho\omega^2}{E}a(x)
\end{eqnarray}
所以，令 $k:=\omega \sqrt{\frac{\rho}{E}}$ 则 $a$ 的解为 $$a=A\mathrm{e}^{\pm\mathrm{i}kx}$$
此处 $k$ 为波数，单位 $\rm{}\frac{1}{s}\sqrt{\frac{kg/m}{kg\cdot m/s^2}}=\frac{1}{m}$ 因此检验 $kx$ 为无量纲量，是合理的。同时我们可以从这个式子重新定义波长，
$$\lambda := \frac{2\pi}{k} $$

言归正传，把最后结果代回 $\psi$ 得到
\begin{eqnarray}
\label{eq:13}
\psi(x,t)&=&A\mathrm{e}^{\mathrm{i}(\pm kx\pm\omega t)}\\
&=&A_1\mathrm{e}^{\mathrm{i}(kx+\omega t)}+A_1^{*}\mathrm{e}^{\mathrm{i}(-kx-\omega t)}+A_2\mathrm{e}^{\mathrm{i}(kx-\omega t)}+A_2^{*}\mathrm{e}^{\mathrm{i}(-kx+\omega t)}
\end{eqnarray}
**** 一般形式
同时，可以定义 $$v=\frac{\omega}{k}$$
效果上如取 $kx-\omega t=0$ 类似于看等高面的变化
于是可以把波动方程写为
\begin{equation}
\label{eq:14}
\frac{\partial^2\psi}{\partial t^2}=v^{2} \frac{\partial^2 \psi}{\partial x^2},\quad \ddot{\psi}-v^2\psi''=0
\end{equation}

(使用点表示对时间求导，撇对空间求导)越来越简洁的形式\footnote{如果你看过普林斯顿数学指南里面甚至把波动方程写成这样}
然而它对我们暂时都作用不大，
因为更强有的数学工具还没有完全具备——时频变换：傅里叶变换。


#+begin_center
回顾
- 解
- 
- 模式
  
#+end_center

* 波动
*** 三角函数正交性：傅里叶变换为什么可以
按照不少物理教材乃至于数学的讲法，我们使用 $\mathrm{e}^{\lambda t}$ 去猜二阶（乃至高阶方程）的解，这为什么合理呢？

涉及到两个问题（并不是说每本书资料会讲这两方面，如果你要查），完备性（complete）和唯一性（unique）
+ 完备性：我的形式可以包含一切，类比3维空间用3个单位正交向量，此处则是 $\mathrm{e}^{\lambda t}$ 可以表达任意（合乎物理）函数
+ 唯一性：只有一个结果，（方法不重要）所得即结果，如：不同方法必然解得等价的
省略了存在性，因为不研究不存在的物理。（牛顿）
华罗庚的书中完全没用，而我们这里想解释的是三角函数的正交性，由于 $\sin(kx)\quad k \mathsf{N}$ 可以得到它，这也是傅里叶级数的基础。
** 横波的流动
*** 推导
*** 反射透射
*** 驻波？
** 电动力学－电磁波
Maxwell 方程组
电磁分离 Hemholz 方程

模式
TE
TM
EM/ME
** 量子力学－波函数
*** 基本形式
\begin{equation}
\label{eq:40}
\mathrm{i}\hbar \frac{\partial \psi}{\partial t}=\hat{H}\psi
\end{equation}
一维情况：

位能井
*** 简谐振子
*** 径向氢原子
* TODO 色散：步伐不再一致
之后研究的很多部分都是不统一带来的（就像研究材料发现种种特性），那么与之前相比差异在哪里呢？
* WAITING 干涉？
* 需要的数学知识
** 线性代数
矩阵、行列式
** 微积分
懂得求导，明白
我们可以直接研究微分方程
** 级数
极限和级数密不可分

* 结束
结束未必是最后写的

给公式标号是论文的做法，我希望最大地追求美观，美是我的规范，只有比较重要的公式我会给予标号已便于引用和找到。
我本来希望对于每一个函数用它较为完全的形式表达，比如
这样至少体现出它完整的自变量信息，可是一来比较麻烦，而且容易把括号混淆，因此就希望读者都是熟悉了物理学混乱标记的优秀者了。

# 框出
写讲义的过程也是学习的过程，我基本完全参考了
# harvard
同时融入了一些自己的理解
加入理论力学、电动力学、量子力学的交叉知识。
可能也没人看吧，毕竟也需要一门名字叫作WAO的课程才能鼓舞起我最大的动力来啃下其中的知识。
#+begin_quote
feryman
#+end_quote
