#+title: 波与振动

* 缘起
倘若对这个课题有一点了解，那么应该了解我们研究波，就是变换波动方程；振动，就是解二阶微分方程。
\begin{equation}
\label{eq:1}
\ddot{x}+\gamma \dot{x}+\omega^2 x=F
\end{equation}
不过，为什么是这样的方程呢？或者它有什么普适的意义。

去掉那些限制，上面方程最简单并且接近本质的形式就是（简单的） Hook 定律： $$m\ddot{x}=-kx$$
我想力本身可以看作是上面这个式子测量出的。
这很符合物理的思维，用最简单（复杂之后我们就换一个词叫优雅）的数学来描述事物间的关系，比如，上面Hook 定律中我们认为力与位移大小成正比，方向相反。

为什么取正比的情况，这自然是一种简单理想考虑问题的方式，一般而言，我们研究的力是（有心）保守力，保守的性质使得我们可以把力写成有势场的梯度 $F=-\frac{\partial V}{\partial r}$,这一点是由数学保证的因为保守意味着对 r 闭合积分为0,因此可以找到一个原函数。
物理中，势能总是复杂的，事实上牛顿公式看似简单（量子力学也是），但能量表达式一旦考虑了势能就无比复杂，这个复杂是数学上的，它难以处理。不过，数学总是可以提供一些强大的工具，对于任意的函数，可以用泰勒级数去逼近，简而言之，对于一个范围内（在下面表达式就是 r_0  附近的点 r ）的势能函数，我们可以用这样的数学形式描述 $$V(r)=V_0+\frac{\partial V}{\partial r}(r-r_0)+\frac{1}{2!}\frac{\partial^2 V}{\partial r^2}(r-r_0)^2+\frac{1}{3!}\frac{\partial^3 V}{\partial r^{3}}(r-r_0)^{3}+...= \sum\limits_{i=0}^{\infty}\frac{1}{i!}\frac{\partial^i V}{\partial r^{i}}(r-_0)^{i} $$

这里使用泰勒展开式对原函数的误差与取的项数有关。如果使用一次函数，那么可以体现出此处 V 的趋势，但对于极值点拟合效果就很差。物理中，极值点当然非常重要，在引入二次项之后，我们就可以很好的描述极值了。当然也可以问，三次是否必要呢，一般而言，越简单越好，实验中，三次项带来的影响非常小，一个二次表达式足以应对普通的情况了（何况3次相当于力与r的二次方有关，这可能就要与非线性打交道了）。

这时，我们看一看我们取的近似场的力学表达式 $F=-\frac{\partial V}{\partial r}=-V_1-V_2\Delta r$

因此，可以想到倘若把kx 的简单系统研究好，这将会对描述复杂系统有极大裨益，或者说，在物理系统里，这属于很常见的形式。

* 二阶常系数线性微分方程
从胡克定律出发，我们可以加入摩擦，外力，得到更复杂的表达式，本质上在数学中而言，就是二阶微分方程。
\begin{equation}
\label{eq:2}
m\ddot{x}=-kx,\quad m\ddot{x}=-kx-b\dot{x},\quad m\ddot{x}=-kx-b\dot{x}+F
\end{equation}
质量不是我们主要考虑的部分（同时为了把方程变得好看），我们换一个更通用的表达 $$\ddot{x}+\gamma \dot{x}+\omega^{2} x=F$$
其中， $\gamma=\frac{b}{m}$ 被称为阻尼系数（它可以是摩擦，也可以在其他系统中，表现为辐射能量）

 $\omega=\sqrt{\frac{k}{m}}$ 是固有频率（其它模型中，同样用 \omega 但就不一定存在一个m,如RLC谐振电路)

对于弹簧振子，类似一个纵波（波的振动与波传播同向）。
# 弹性模量
** 解方程
若对二阶方程不熟悉，甚至于希望借由波动方程学习解微分方程者，这里给出一个从简单到复杂的案例，望读者自主思考其中一以贯之的思想。
自然的，方程即约束（反过来约束条件就是方程）约束的存在使得我们感兴趣的对象（譬如波的x）有决定性唯一性的表象，这就是我们要尝试得到方程的解。像代数方程将未知数组合升幂，它的解是数，微分方程用求导数给出未知函数的关系，它的解是函数。我们有二次高次代数方程，而区分微分方程时，还会使用阶，这里的阶就是求导次数，比如 (\ref{eq:2}) 都是是二阶微分方程，因为最高次导数都是$\ddot{x}$,同时还可以称它为常系数一次线性， [to eb added]

解 $m\ddot{x}=-kx$ 是“简单”的，仅仅（乃至于只能，故“我们”说简单）凭数学洞见可以发现它的解 $$x=C_1\mathrm{e}^{\sqrt{\frac{k}{m}}it}+C_2\mathrm{e}^{-\sqrt{\frac{k}{m}}t}$$
[to be added]

* 多个振子——模式
第一见到模式，大多人应该感到奇怪，但从多个振子的组合运动推导明白，把慢变快变写清楚，大体就可以明白所谓模式即拆分复杂现象的简单形式（而我们正是乐于使用简单形式来组合描述，当你了解后你也应该会感到精彩的，同时模式mode 这个翻译还是有点不太好）。

初看似乎多个振子将是十分复杂的问题，但如果读者感到疑惑困难后文附上两个振子情况以供参考。暂时忽略摩擦不施外力（之后需要时也很方便加上），并且所有弹簧弹性系数相同。我们先写出方程

\begin{eqnarray}
\label{eq:5}
m\ddot{x_1} & = & -kx_1-k(x_1-x_2) \\
m\ddot{x_2} & = & -k(x_2-x_1)-k(x_2-x_3)\\
\cdots\\
m\ddot{x_i} & = & -k(x_i-x_{i-1})-k(x_i-x_{i+1})\\
\cdots\\
m\ddot{x_n} & = & -k(x_n-x_{n-1})-k(x_n)
\end{eqnarray}
用矩阵的形式简写，

(\ref{eq:5})
直接用作尝试解


* 波动方程
  
x
